# Generated by Django 5.2.1 on 2025-05-24 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('codigo_calif', models.AutoField(primary_key=True, serialize=False)),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado')], default='habilitado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado')], default='habilitado', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Jefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('numero_seguridad', models.CharField(max_length=4)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_serie', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año_compra', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado')], max_length=15)),
                ('precio_alquiler_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.localidad')),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.politica')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendienteRetiro', 'Pendiente de retiro'), ('enCurso', 'En curso'), ('finalizado', 'Finalizado')], default='pendienteRetiro', max_length=20)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.calificacion')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.cliente')),
                ('codigo_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha', models.DateField()),
                ('codigo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.maquinaria')),
            ],
        ),
    ]
