# Generated by Django 5.2.1 on 2025-05-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='precio_alquiler_diario',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
