# Generated by Django 5.2.1 on 2025-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('jefe', 'Jefe')], default='cliente', max_length=10),
        ),
    ]
