# Generated by Django 5.2.1 on 2025-06-01 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_remove_cliente_edad_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='General.tarjeta'),
        ),
    ]
