# Generated by Django 5.2.1 on 2025-05-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_cliente_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('jefe', 'Jefe'), ('empleados', 'Empleados')], default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado')], default='habilitado', max_length=15),
        ),
    ]
