# Generated by Django 5.2.1 on 2025-06-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alquiler_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
