# Generated by Django 5.2.1 on 2025-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_alter_tarjeta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
