# Generated by Django 5.2.1 on 2025-06-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("General", "0004_alter_tarjeta_monto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquinaria",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="General.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="tarjeta",
            name="monto",
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
