# Generated by Django 5.2.1 on 2025-06-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0005_alter_maquinaria_localidad_alter_tarjeta_monto'),
        ('General', '0005_alter_tarjeta_monto'),
    ]

    operations = [
    ]
