# Generated by Django 5.2.1 on 2025-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_merge_20250601_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
