# Generated by Django 5.2.1 on 2025-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0009_remove_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dni',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
        ),
    ]
