# Generated by Django 5.2.1 on 2025-06-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0010_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
    ]
