# Generated by Django 5.2.1 on 2025-06-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0012_cliente_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='localidad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alquiler',
            name='marca',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alquiler',
            name='modelo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alquiler',
            name='politica_cancelacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado'), ('eliminado', 'Eliminado')], default='habilitado', max_length=15),
        ),
    ]
