# Generated by Django 5.2.2 on 2025-06-21 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0013_alquiler_localidad_alquiler_marca_alquiler_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
