# Generated by Django 5.2.1 on 2025-07-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0014_cliente_fecha_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='precio',
            new_name='precioPorDia',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='precioTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('pendienteRetiro', 'Pendiente de retiro'), ('enCurso', 'En curso'), ('pendienteDevolucion', 'Pendiente de devolución'), ('finalizado', 'Finalizado')], default='pendienteRetiro', max_length=20),
        ),
    ]
