# Generated by Django 5.2.1 on 2025-07-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0015_rename_precio_alquiler_preciopordia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='precioTotal',
            new_name='precio',
        ),
    ]
