# Generated by Django 5.2.1 on 2025-07-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0016_rename_preciototal_alquiler_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='telefono',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
