# Generated by Django 5.2.2 on 2025-07-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0017_localidad_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
