# Generated by Django 5.2.2 on 2025-07-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0018_alquiler_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='General.cliente'),
        ),
    ]
