# Generated by Django 5.2.2 on 2025-07-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0019_calificacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
