# Generated by Django 5.2.2 on 2025-07-08 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0020_maquinaria_fecha_habilitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='General.maquinaria')),
            ],
        ),
    ]
