# Generated by Django 5.2.1 on 2025-07-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0021_observacionmaquinaria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObservacionMaquinaria',
        ),
    ]
