# Generated by Django 5.2.1 on 2025-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("General", "0022_delete_observacionmaquinaria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localidad",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
