# Generated by Django 5.2.1 on 2025-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("General", "0023_alter_localidad_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localidad",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
