<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-28 21:01
=======
# Generated by Django 5.2.1 on 2025-05-28 21:17
>>>>>>> fc8cc2c (agregar maquina terminado)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('ApartadoCliente', '0001_initial'),
=======
        ("ApartadoCliente", "0001_initial"),
>>>>>>> fc8cc2c (agregar maquina terminado)
    ]

    operations = [
        migrations.DeleteModel(
<<<<<<< HEAD
            name='Cliente',
=======
            name="Cliente",
>>>>>>> fc8cc2c (agregar maquina terminado)
        ),
    ]
