# Generated by Django 5.2.1 on 2025-05-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApartadoCliente', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
