# Generated by Django 5.2.2 on 2025-07-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApartadoMaquina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='fecha_habilitacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
